# Generated by Django 4.0.4 on 2022-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASsheet',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(blank=True, max_length=100, null=True, verbose_name='업체명')),
                ('rg_date', models.DateTimeField(auto_now_add=True, verbose_name='고객 접수일')),
                ('rp_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='처리 완료일')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품 이름')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('option', models.TextField(blank=True, null=True, verbose_name='의견')),
                ('finish', models.CharField(blank=True, max_length=10, null=True, verbose_name='완료 여부')),
            ],
            options={
                'verbose_name': 'AS접수',
                'verbose_name_plural': 'AS접수',
                'db_table': 'assheet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsUploadFile',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('uploadedFile', models.FileField(blank=True, upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('sheet_no', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'AS file 업로드',
                'verbose_name_plural': 'AS file 업로드',
                'db_table': 'ASuploadfile',
                'managed': True,
            },
        ),
    ]
