# Generated by Django 4.0.4 on 2022-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsUploadFile',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('uploadedFile', models.FileField(blank=True, upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('sheet_no', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'AS file 업로드',
                'verbose_name_plural': 'AS file 업로드',
                'db_table': 'ASuploadfile',
                'managed': True,
            },
        ),
    ]
