# Generated by Django 4.0.4 on 2022-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asregister', '0002_alter_asuploadfile_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuploadfile',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
