# Generated by Django 4.0.4 on 2022-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asregister', '0002_alter_assheet_cphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assheet',
            name='quantity',
        ),
        migrations.AddField(
            model_name='assheet',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='assheet',
            name='cuser',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='요청자'),
        ),
    ]
