# Generated by Django 4.0.4 on 2022-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asregister', '0003_remove_assheet_quantity_assheet_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assheet',
            name='site',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='프로젝트명'),
        ),
    ]
