# Generated by Django 4.0.4 on 2022-05-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asregister', '0004_alter_asuploadfile_sheet_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assheet',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
