# Generated by Django 4.0.4 on 2022-06-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asregister', '0005_assheet_after_serial_alter_assheet_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assheet',
            name='asaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='as처리내역'),
        ),
        migrations.AddField(
            model_name='assheet',
            name='la_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대분류'),
        ),
        migrations.AddField(
            model_name='assheet',
            name='me_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='중분류'),
        ),
        migrations.AddField(
            model_name='assheet',
            name='sm_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소분류'),
        ),
        migrations.AlterField(
            model_name='assheet',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제품 이름'),
        ),
    ]
