# Generated by Django 4.0.4 on 2022-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSheet',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('rg_date', models.DateTimeField(auto_now_add=True)),
                ('rp_date', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(max_length=100, verbose_name='제품 이름')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('per_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True)),
                ('new_old', models.CharField(default='신규', max_length=25, null=True, verbose_name='구분')),
                ('business_number', models.IntegerField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=100, null=True, verbose_name='업체명')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('option', models.TextField(blank=True, null=True, verbose_name='의견')),
                ('finish', models.CharField(blank=True, max_length=10, null=True)),
                ('user_dept', models.CharField(blank=True, max_length=20, null=True, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '견적',
                'verbose_name_plural': '견적',
                'db_table': 'estimatesheet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('uploadedFile', models.FileField(blank=True, upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('sheet_no', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': '업로드',
                'verbose_name_plural': '업로드',
                'db_table': 'uploadfile',
                'managed': True,
            },
        ),
    ]
