# Generated by Django 4.0.4 on 2022-04-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSheet',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('rg_date', models.DateTimeField(auto_now_add=True)),
                ('rp_date', models.DateTimeField(auto_now=True)),
                ('file_name', models.FileField(max_length=200, upload_to='', verbose_name='파일 이름')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품 이름')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('per_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_old', models.CharField(max_length=25, verbose_name='구분')),
                ('business_number', models.IntegerField()),
                ('company_name', models.CharField(max_length=100, verbose_name='업체명')),
                ('memo', models.TextField(verbose_name='비고')),
            ],
            options={
                'verbose_name': '견적',
                'verbose_name_plural': '견적',
                'db_table': 'estimatesheet',
                'managed': True,
            },
        ),
    ]
