# Generated by Django 4.0.4 on 2022-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='rg_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
