# Generated by Django 4.0.4 on 2022-06-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_sheet',
            name='enter_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='입력 수량'),
        ),
    ]
