# Generated by Django 4.0.4 on 2022-05-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='estimatesheet',
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='sheet_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isscm.estimatesheet'),
        ),
    ]
