# Generated by Django 4.0.4 on 2022-05-04 15:27

from django.db import migrations, models
import isscm.utils


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuploadfile',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to=isscm.utils.rename_file_to_uuid),
        ),
    ]
