# Generated by Django 4.0.4 on 2022-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='sub_sheet',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='담당자'),
        ),
    ]
