# Generated by Django 4.0.4 on 2022-05-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_alter_estimatesheet_per_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
