# Generated by Django 4.0.4 on 2022-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_product_info_user_name_sub_sheet_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='no',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
