# Generated by Django 4.0.4 on 2022-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_ordersheet_rg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersheet',
            name='rg_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
