# Generated by Django 4.0.4 on 2022-05-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_remove_uploadfile_estimatesheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='sheet_no',
            field=models.ForeignKey(db_column='sheet_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='isscm.estimatesheet'),
        ),
    ]
