# Generated by Django 4.0.4 on 2022-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_main_sheet_sub_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_sheet',
            name='rp_date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='마감일자'),
        ),
    ]
