# Generated by Django 4.0.4 on 2022-04-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_remove_estimatesheet_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatesheet',
            old_name='company_name',
            new_name='cname',
        ),
    ]
