# Generated by Django 4.0.4 on 2022-06-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0002_sub_sheet_enter_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_sheet',
            name='end_date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='종료일자'),
        ),
        migrations.AlterField(
            model_name='main_sheet',
            name='rp_date',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='마감 요청일자'),
        ),
    ]
