# Generated by Django 4.0.4 on 2022-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_alter_uploadfile_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuploadfile',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
