# Generated by Django 4.0.4 on 2022-05-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_alter_uploadfile_sheet_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderuploadfile',
            name='sheet_no',
            field=models.ForeignKey(db_column='sheet_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='isscm.ordersheet'),
        ),
    ]
