# Generated by Django 4.0.4 on 2022-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_alter_productdb_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='제목')),
                ('user_dept', models.CharField(blank=True, max_length=10, null=True, verbose_name='부서명')),
                ('user_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='작성자')),
                ('start_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='시작일자')),
                ('end_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='종료일자')),
                ('rg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'notice',
                'managed': True,
            },
        ),
    ]
