# Generated by Django 4.0.4 on 2022-04-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_rename_company_name_estimatesheet_cname'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesheet',
            name='memo',
            field=models.TextField(null=True, verbose_name='비고'),
        ),
    ]
