# Generated by Django 4.0.4 on 2022-05-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_alter_ordersheet_rg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesheet',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='성함'),
        ),
    ]
