# Generated by Django 4.0.4 on 2022-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_alter_main_sheet_rp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_sheet',
            name='m_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='메인 title'),
        ),
    ]
