# Generated by Django 4.0.4 on 2022-05-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0003_alter_estimatesheet_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='quantity',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
