# Generated by Django 4.0.4 on 2022-05-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0004_alter_orderuploadfile_sheet_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdb',
            options={'managed': True},
        ),
    ]
