# Generated by Django 4.0.4 on 2022-04-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0004_estimatesheet_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '업로드',
                'verbose_name_plural': '업로드',
                'db_table': 'uploadfile',
                'managed': True,
            },
        ),
    ]
