# Generated by Django 4.0.4 on 2022-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0004_orderuploadfile_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
