# Generated by Django 4.0.4 on 2022-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0004_alter_estimatesheet_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesheet',
            name='estitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
