# Generated by Django 4.0.4 on 2022-05-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0004_estimatesheet_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='성함'),
        ),
    ]
