# Generated by Django 4.0.4 on 2022-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0005_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
