# Generated by Django 4.0.4 on 2022-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0005_alter_productdb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='per_price',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='total_price',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
