# Generated by Django 4.0.4 on 2022-05-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0005_estimatesheet_estitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordersheet',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('rp_date', models.CharField(blank=True, max_length=50, null=True)),
                ('odtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='발주명')),
                ('product_name', models.CharField(max_length=100, verbose_name='제품 이름')),
                ('quantity', models.TextField(blank=True, default=0, null=True, verbose_name='수량')),
                ('per_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=18, null=True)),
                ('new_old', models.CharField(default='신규', max_length=25, null=True, verbose_name='구분')),
                ('business_number', models.IntegerField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=100, null=True, verbose_name='업체명')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('option', models.TextField(blank=True, null=True, verbose_name='의견')),
                ('user_dept', models.CharField(blank=True, max_length=20, null=True, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '발주 입력',
                'verbose_name_plural': '발주 입력',
                'db_table': 'ordersheet',
                'managed': True,
            },
        ),
    ]
