# Generated by Django 4.0.4 on 2022-06-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0005_product_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_management',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='제품명'),
        ),
    ]
