# Generated by Django 4.0.4 on 2022-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0006_ordersheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersheet',
            name='essheet_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
