# Generated by Django 4.0.4 on 2022-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0006_uploadfile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='cname',
            field=models.CharField(max_length=100, null=True, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='new_old',
            field=models.CharField(max_length=25, null=True, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='per_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
