# Generated by Django 4.0.4 on 2022-06-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0006_alter_product_management_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_management',
            name='info_id',
            field=models.ForeignKey(db_column='info_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='isscm.product_info'),
        ),
    ]
