# Generated by Django 4.0.4 on 2022-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0007_alter_estimatesheet_per_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersheet',
            name='per_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ordersheet',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='ordersheet',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
