# Generated by Django 4.0.4 on 2022-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0007_alter_estimatesheet_cname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='business_number',
            field=models.IntegerField(null=True),
        ),
    ]
