# Generated by Django 4.0.4 on 2022-06-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0008_alter_product_management_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_management',
            name='info_id',
        ),
    ]
