# Generated by Django 4.0.4 on 2022-06-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0009_remove_product_management_info_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_management',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일자'),
        ),
    ]
