# Generated by Django 4.0.4 on 2022-04-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0009_remove_uploadfile_id_uploadfile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='no',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='no'),
        ),
    ]
