# Generated by Django 4.0.4 on 2022-04-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0010_alter_uploadfile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
