# Generated by Django 4.0.4 on 2022-04-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0011_alter_uploadfile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
