# Generated by Django 4.0.4 on 2022-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0012_delete_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '업로드',
                'verbose_name_plural': '업로드',
                'db_table': 'uploadfile',
                'managed': True,
            },
        ),
    ]
