# Generated by Django 4.0.4 on 2022-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0014_alter_uploadfile_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='rp_date',
            field=models.DateTimeField(),
        ),
    ]
