# Generated by Django 4.0.4 on 2022-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0015_alter_estimatesheet_rp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesheet',
            name='option',
            field=models.TextField(null=True, verbose_name='의견'),
        ),
    ]
