# Generated by Django 4.0.4 on 2022-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0016_estimatesheet_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='rp_date',
            field=models.DateTimeField(null=True),
        ),
    ]
