# Generated by Django 4.0.4 on 2022-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0018_estimatesheet_sheet_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatesheet',
            name='sheet_no',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='sheet_no',
            field=models.IntegerField(null=True),
        ),
    ]
