# Generated by Django 4.0.4 on 2022-04-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0019_remove_estimatesheet_sheet_no_uploadfile_sheet_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='new_old',
            field=models.CharField(default='신규', max_length=25, null=True, verbose_name='구분'),
        ),
    ]
