# Generated by Django 4.0.4 on 2022-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0020_alter_estimatesheet_new_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='business_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='cname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='option',
            field=models.TextField(blank=True, null=True, verbose_name='의견'),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='per_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='rp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
