# Generated by Django 4.0.4 on 2022-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0021_alter_estimatesheet_business_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='per_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='estimatesheet',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
