# Generated by Django 4.0.4 on 2022-04-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0023_alter_estimatesheet_rp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesheet',
            name='finish',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
