# Generated by Django 4.0.4 on 2022-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0024_estimatesheet_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesheet',
            name='fileck',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
