# Generated by Django 4.0.4 on 2022-04-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0025_estimatesheet_fileck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatesheet',
            name='fileck',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
