# Generated by Django 4.0.4 on 2022-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isscm', '0026_alter_estimatesheet_fileck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatesheet',
            name='fileck',
        ),
        migrations.AddField(
            model_name='estimatesheet',
            name='user_dept',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='부서명'),
        ),
    ]
