# Generated by Django 4.0.4 on 2022-05-09 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDb',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('ccode', models.IntegerField()),
                ('cname', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=50, null=True)),
                ('owner', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=25, null=True)),
                ('cphone', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=25, null=True)),
                ('cemail', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=30, null=True)),
                ('smanager', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=25, null=True)),
                ('rg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'company_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cmanager', models.CharField(max_length=100)),
                ('smanager', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{2,3}-\\d{3,4}-\\d{4}')])),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('adress', models.CharField(blank=True, max_length=800, null=True)),
                ('homepage', models.CharField(blank=True, max_length=800, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
