# Generated by Django 4.0.4 on 2022-04-17 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cmanager', models.CharField(max_length=100)),
                ('smanager', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{2,3}-\\d{3,4}-\\d{4}')])),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True)),
                ('adress', models.CharField(blank=True, max_length=800, null=True)),
                ('homepage', models.CharField(blank=True, max_length=800, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
