# Generated by Django 4.0.4 on 2022-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
