# Generated by Django 4.0.4 on 2022-05-01 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='아이디')),
                ('cname', models.CharField(max_length=100, verbose_name='업체명')),
                ('user_pw', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('user_phone', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='\\d{2,3}-\\d{3,4}-\\d{4}')], verbose_name='연락처')),
                ('user_email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='이메일')),
                ('user_date', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.IntegerField(default=1)),
                ('user_dept', models.CharField(blank=True, max_length=20, null=True, verbose_name='부서명')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'accounts',
            },
        ),
    ]
