# Generated by Django 4.0.4 on 2022-04-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDb',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('ccode', models.IntegerField()),
                ('cname', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=50, null=True)),
                ('owner', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=25, null=True)),
                ('cphone', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=25, null=True)),
                ('cemail', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=30, null=True)),
                ('smanager', models.CharField(blank=True, db_collation='utf8mb4_general_ci', max_length=25, null=True)),
                ('rg_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'company_db',
                'managed': False,
            },
        ),
    ]
