# Generated by Django 4.0.4 on 2022-04-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companydb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDb',
        ),
    ]
