# Generated by Django 4.0.4 on 2022-04-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_companydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_dept',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='부서명'),
        ),
    ]
