# Generated by Django 4.0.4 on 2022-05-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_sheet',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='제목')),
                ('cname', models.CharField(blank=True, max_length=100, null=True, verbose_name='업체명')),
                ('rg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('type', models.CharField(max_length=30, verbose_name='유형')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
            ],
            options={
                'verbose_name': '문의글',
                'verbose_name_plural': '문의글',
                'db_table': 'questionsheet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='question_comment',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('rg_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('register', models.CharField(blank=True, max_length=30, null=True, verbose_name='등록자')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('que_no', models.ForeignKey(db_column='que_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question_sheet')),
            ],
            options={
                'verbose_name': '문의댓글',
                'verbose_name_plural': '문의댓글',
                'db_table': 'quecomment',
                'managed': True,
            },
        ),
    ]
