# Generated by Django 4.0.4 on 2022-05-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_que_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question_comment'),
        ),
    ]
