# Generated by Django 4.0.4 on 2022-05-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_sheet_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_sheet',
            name='comm',
        ),
        migrations.AddField(
            model_name='question_comment',
            name='comm',
            field=models.PositiveIntegerField(null=True, verbose_name='댓글수'),
        ),
    ]
